apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cf-operator-quarks-job
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cf-operator-quarks-job
subjects:
- kind: ServiceAccount
  name: cf-operator-quarks-job
  namespace: default
