apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: quarks-job
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: quarks-job
subjects:
- kind: ServiceAccount
  name: quarks-job
