apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: router
  name: router-public
  namespace: default
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app.kubernetes.io/component: router
    app.kubernetes.io/instance: kubecf
    app.kubernetes.io/version: v0.0.0-a4a9bd5
  type: LoadBalancer
