apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: ssh-proxy
  name: ssh-proxy-public
  namespace: default
spec:
  ports:
  - name: ssh
    port: 2222
    protocol: TCP
    targetPort: 2222
  selector:
    app.kubernetes.io/component: ssh-proxy
    app.kubernetes.io/instance: kubecf
    app.kubernetes.io/version: v0.0.0-a4a9bd5
  type: LoadBalancer
